Ecommerce/Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerceApp/',include('ecommerceApp.urls')),
    path('search/',include('searchApp.urls')),
    path('cartApp', include('cartApp.urls')),

]


if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ecommerce/cartApp/urls.py
from django.urls import path
from .import views

app_name = 'cartApp'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

Ecommerce/ecommerceApp/urls.py
from django.urls import path

from ecommerceApp import views
app_name='ecommerceApp'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
]

Ecommerce/searchApp/urls.py
from django.urls import path
from .import views
app_name = 'searchApp'

urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

Ecommerce/cartApp/models.py
from django.db import models
from django.db import models
from ecommerceApp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

Ecommerce/ecommerceApp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecommerceApp:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)
class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image= models.ImageField(upload_to='category', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def get_url(self):
        return reverse('ecommerceApp:prodCatdetail',args=[self.category.slug,self.slug])
    def __str__(self):
        return '{}'.format(self.name)

Ecommerce/searchApp/models.py
from django.db import models

# Create your models here.

Ecommerce/cartApp/views.py
import requests
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceApp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=cart_id(request))
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cartApp:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartApp:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cartApp:cart_detail')










# Create your views here.

Ecommerce/ecommerceApp/views.py
from django.shortcuts import render, get_object_or_404

from ecommerceApp.models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
def allProdCat(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        product_list=Product.objects.all().filter(available=True)
    paginator=Paginator(product_list,5)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

Ecommerce/searchApp/views.py
from django.shortcuts import render
from ecommerceApp.models import Product
from django.db.models import Q


# Create your views here.
def searchResult(request):
    products=None
    Query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

Ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/1e6b83f135.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="stylesheet"href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>{% block title %} {% endblock %}</title>

</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}

{% endblock %}
    </div>

{% include 'footer.html' %}
<script src=" {% static 'js/popper.min.js' %}"></script>
<script src=" {% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

Ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
this is the cart page procee to review your item and place the order
{% endblock %}
{% block title %}
cart mahiTeknow pVT LTD
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div  class="text-center">
        <br>
        <h1 class="text-center my_title"> your shopping cart</h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'ecommerce:allProdCat' %}">Here</a> to continue shopping

        </p>
    </div>
</div>

{% else %}
<div>
<div class="text-center">
    <br>
    <h1  class="text-center my_title"> your shopping cart</h1>
    <br>


    </div>
</div>

<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    your Items
                </th>
            </tr>


            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cat_item.product.get_absolute_url">
                        <img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image">
                    </a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Price:${{cart_item.product.price}}
                    <br>
                    Qty:{{cart_item.quantity}} * $ {{ cart_item}}
                </td>
                <td>

                  $ {{cart_item.sub_total}}
                </td>

                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                <a href="{% url 'cartApp:add_cart' cart_item.product.id %} " class="custom_icon"> <i class="fa-solid fa-cart-plus custom_icon"></i></a>
                &nbsp;<a href="{% url 'cartApp:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-minus custom_icon"></i></a>
                &nbsp;<a href="{% url 'cartApp:full_remove' cart_item.product.id %} " class="custom_icon"> <i class="fa fa-trash custom_icon"></i></a>
                </td>


                    {% else %}
                <td>
                &nbsp;<a href="{% url 'cartApp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                &nbsp;<a href="{% url 'cartApp:full_remove' cart_item.product.id %} " class="custom_icon"> <i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                CheckOut
            </tr>

            </thead>
            <tbody>
            <tr>
                <td> please review your shopping cart item before proceeding with the order payment</td>
            </tr>
            <tr>
                <td class="text-left">
                    yourTotal is: <strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>

        </table>
        <div class="mx_auto">
        <a href="{% url 'ecommerceApp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">continue shopping</a>

        </div>

    </div>
</div>
{% endif %}

{% endblock %}

Ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        welcome to mahiteknow store where you can buy new thongs
    {% endif %}
    {% endblock %}
{% block title %}
{% if category %}
    {{ category.name}} Mahi- store
{% else %}
see our new collections
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div class="row my_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'ecommerceApp:allProdCat' %}">our product selection</a></p>
    </div>
</div>
{% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" style="width:150px;height:150px;">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'image/banner1.jpg' %}" alt="our products">
    </div>
<div>
    <h1 class="text-center my_title">our product collections</h1>
    <p class="text-justify">dummy texts</p>

</div>
{% endif %}

<div class="container">
    <div class="row">

        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"> <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:150px;height:150px;"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
             </div>
        </div>
        {% endfor %}

    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}

        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {%endif %}">{{pg}}</a>
            {% endfor %}

        </div>

        {% endif %}

    </div>
    <br>
</div>
{% endblock %}

Ecommerce/templates/footer.html
<div class="footer nav-bar-fixed-bottom my_footer">
    <p class="text-center">
        &copy;MAhi Teknow All right reserved </p>

</div>

Ecommerce/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerceApp:allProdCat' %}"><img src="{% static 'image/logo.png' %}" alt="logoImage" width="180px" height="100px"></a>
    </center>
</header>

Ecommerce/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>home page</h1>
</body>
</html>

Ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerceAPP' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecommerceApp:allProdCat' %}">All Product</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{cat.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
        {% if  item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cartApp:cart_detail' %}"><i class="fa-solid fa-cart-shopping cart">({{item_count}})</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchApp:searchResult' %}">
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

Ecommerce/templates/product.html
{% extends 'base.html' %}
{%load static %}
{% block metadescription %}
{{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
{% if category %}
{{ product.name}} mY_E_com
{% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_class">
    <div class="mx_auto">
        <p><a href="{% url 'ecommerceApp:allProdCat' %}">HOME</a>
            <a href="{{product.category.get_url}}">{{product.category}}</a>  | {{ product.name }}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">


<div class="min-width:18rem;">
    <img src="{{product.image.url}}" alt="{{product.name}}">

</div>
    </div>
</div>
<div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <h1 class="my_prod_title">{{ product.name}}</h1>
        <p>{{product.price}}</p>
        <p class="my_title">Product Description</p>
        <p class="text-justify my_prod_text">{{product.description}}</p>
        {% if product.stock <= 0 %}
        <p class="text-justify my_prod_text"> ><b> out of stock</b></p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cartApp:add_cart' product.id %}">add to cart</a>
        {% endif %}
    </div>
</div>
    </div>
{% endblock %}

Ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

       we have variety of products

    {% endblock %}
{% block title %}
search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">you have searched for<b>"{{query}}"</b></p>


</div>
<div class="container">
    <div class="row max_auto">

        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"> <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
             </div>
        </div>
        {% empty %}
        <div class="row amx_auto">
            <p class="text-center my_search_text">0 result found</p>

        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}